fieldLayouts:
  f115f22c-568e-4d0d-bc47-4412b974a0fd:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b0252967-0e5a-422f-bd99-790f68762e58
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ef74887a-7a07-4977-84c2-c7793e0529a5 # Header Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ad675966-96b4-4557-a77d-b562cc61eec5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: cda0e34b-d94a-41a0-8ef6-e1dd1974c771
        userCondition: null
handle: contact
hasTitleField: false
name: Contact
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
