color: null
fieldLayouts:
  02c6344e-b5e8-4637-8413-e5d525e95a8d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4e702683-da9c-4176-be5a-d246b253c2a9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: ef74887a-7a07-4977-84c2-c7793e0529a5 # Header Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 99d86c54-a555-4bd5-b2e7-c0b80c829452
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: ed2878ee-102f-406d-b62d-3d231fd7460b # Header Image Alt
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 88346f17-70f1-46da-aad5-301088b01d56
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 1e7716dd-da4e-4a82-9a4a-f4eb04970454 # ListenCTA
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4738f4db-3646-4130-aeb3-27aa90a60169
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8fccdca2-2a59-42e2-a7dc-14a49429c91a
        userCondition: null
handle: home
hasTitleField: false
icon: null
name: Home
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
