fieldLayouts:
  d15573eb-6d9d-4d33-ae1b-795d6d43a5b4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c2c79a24-bc84-435f-9ebc-8883c8925090
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2d05a2b8-fa1f-4237-9abc-77880f943975 # Page Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 17f4074b-df91-4b14-a093-a61dcdea1cd8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ef74887a-7a07-4977-84c2-c7793e0529a5 # Header Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4ec92d0e-0089-40aa-a6a7-4598926c8b5e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0faa9768-b53e-4216-a53d-7812596fdc94 # Videos
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1f99f4ea-77c5-47b6-af3b-2c2c5f7a65eb
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f6f15de1-9183-4a46-b0ff-3391c768838a
        userCondition: null
handle: media
hasTitleField: false
name: Media
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
