color: null
fieldLayouts:
  14b2cdef-050c-4adc-ae21-07365e4db67a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 161bdf11-5dd5-4f4d-a875-e4b5a42efc22
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 2d05a2b8-fa1f-4237-9abc-77880f943975 # Page Title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: de71390e-cbf6-4c6d-bf3a-d60320892928
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: ef74887a-7a07-4977-84c2-c7793e0529a5 # Header Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f3d93288-b6c4-48ac-8199-da07ea5505ab
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 024543db-feed-428a-922b-5c42d8374aaa # Album CTA
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 24b94d4e-46e6-4a86-8e29-75b05a9d8eeb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 569d7efe-e957-4fa0-a49a-c4b1b8fba23b # Album Cover
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 53b7f7d0-5f0e-489f-80a6-6eabc70932ca
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: ed2878ee-102f-406d-b62d-3d231fd7460b # Header Image Alt
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 251c9414-05ef-4cbf-89e7-1dcca356add1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 66bdc090-1029-4da8-a10f-8e0bc54176bb # spotifyIframes
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3fbb8013-62c0-47e9-aae6-24ebf0b7dccd
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d2f9bc03-9464-451a-806e-c7cf57836dd7
        userCondition: null
handle: music
hasTitleField: false
icon: null
name: Music
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
