fieldLayouts:
  2b492d9d-fdea-4ecf-9b4e-da23f3f37462:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: a4fdb31e-5854-4847-923b-ecb7e2eb7468
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: eef00113-cbb0-4694-a0b5-70dbfd82c243 # Internal or External
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 77f870f7-c4cf-4199-9076-9b2d900c99bb
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: 17303915-9872-43ed-9684-e3ae9e8d6099 # Open In new Tab
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4497ebff-112a-4ddf-84af-01512f0c95e4
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\elements\conditions\entries\TypeConditionRule
                  operator: in
                  uid: 97958a2e-81c8-4714-9f7d-f207f4bd6a85
                  values:
                    - d2d8c823-93e6-4574-a238-533954b4b8b9 # Default
                -
                  class: craft\fields\conditions\LightswitchFieldConditionRule
                  fieldUid: eef00113-cbb0-4694-a0b5-70dbfd82c243 # Internal or External
                  uid: 98c173bd-7c8d-4df7-b0a2-8c321b29eda2
                  value: true
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: df3eb26c-d215-44f0-a235-413cdb54c672 # External Page
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9919e063-4421-44a3-8560-8312f2c6f5d2
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\LightswitchFieldConditionRule
                  fieldUid: eef00113-cbb0-4694-a0b5-70dbfd82c243 # Internal or External
                  uid: da9fdfb6-f74a-4d2c-bfd8-3f4616c1eb78
                  value: false
                -
                  class: craft\elements\conditions\entries\TypeConditionRule
                  operator: in
                  uid: 7b8f742b-de5e-427b-9495-5a8cf3624d57
                  values:
                    - d2d8c823-93e6-4574-a238-533954b4b8b9 # Default
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 20cc593a-1deb-4cbb-b161-ee53c5a114d9 # Entry
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 84dc8940-8450-44e8-bd29-a12af88c7e8d
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 73e62626-afde-44dc-ac64-7a08bbf45521
        userCondition: null
handle: navigation_default
hasTitleField: true
name: Default
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: navitem
titleTranslationKeyFormat: null
titleTranslationMethod: site
