color: null
fieldLayouts:
  52c34cd2-4af3-430b-bfef-270bebc6e0f0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 3a7a59c6-a8f1-4c6a-84f9-4815b49830b7
            handle: null
            includeInCards: true
            instructions: null
            label: 'Nav Link Title'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 01d3d5c6-7946-4532-938e-cdaa7561b8b7
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: a2058849-7eb6-49c3-9d32-a1a3a06e6908
            handle: null
            includeInCards: false
            instructions: null
            label: 'Nav Page Link'
            providesThumbs: true
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 041354d6-b3b4-4950-9bbe-e581b377d898
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 5e9ff26e-2257-4ead-9f41-4ebf176eda38
            handle: null
            includeInCards: false
            instructions: null
            label: 'Nav External Link'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 461521e8-89cf-49ca-8c30-9dae0aefea8b
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 58b1883a-1d68-41e3-8621-acdaba4a6db0
        userCondition: null
handle: navItem
hasTitleField: false
icon: null
name: 'Nav Item'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
