color: null
fieldLayouts:
  2a92bd16-f26e-4f57-9b79-c622375ebba9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: fa48dafe-74b9-453b-b830-4cf86fcfa73e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 2d05a2b8-fa1f-4237-9abc-77880f943975 # Page Title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4814a600-495f-465f-898b-c572d5076839
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: ef74887a-7a07-4977-84c2-c7793e0529a5 # Header Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 37216979-c156-4015-94c7-0c32cf19ade6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f249e99b-fc21-497b-86cb-f08ba732897c
        userCondition: null
handle: tour
hasTitleField: false
icon: null
name: Tour
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
