headingLevels:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
name: Default
options:
  alignment:
    options:
      - left
      - right
  code:
    indentSequence: '  '
  htmlSupport:
    allow:
      -
        attributes: true
        classes: true
        styles: true
toolbar:
  - sourceEditing
  - '|'
  - heading
  - '|'
  - blockQuote
  - codeBlock
  - bold
  - italic
  - strikethrough
  - alignment
  - bulletedList
  - numberedList
  - insertImage
  - link
  - htmlEmbed
  - mediaEmbed
