fieldLayouts:
  bed4b1dc-74a8-4dd7-bfef-3b0c6a1c3011:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 7f785c7c-edf8-4e00-aa03-2d266c20edbb
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0989bf7b-9ece-4630-83d6-361d28a7f58d
        userCondition: null
fs: uploads
handle: uploads
name: Uploads
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
