columnSuffix: null
handle: ctaButtons
instructions: 'these are call to action buttons in the home page under the header title and image'
name: 'CTA Buttons'
searchable: false
settings:
  createButtonLabel: null
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 33fc222b-d308-432c-b70c-c128f4df6783 # button
  includeTableView: false
  maxEntries: 10
  minEntries: 1
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
