columnSuffix: null
contentColumnType: string
handle: ctaButtons
instructions: 'these are call to action buttons in the home page under the header title and image'
name: 'CTA Buttons'
searchable: false
settings:
  entryTypes:
    -
      uid: 33fc222b-d308-432c-b70c-c128f4df6783
  maxEntries: 10
  minEntries: 1
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
