columnSuffix: null
contentColumnType: text
handle: customContent
instructions: "This could be any text content you'd like. This can be a bio section or an about field or a simple announcement."
name: 'Custom Content'
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  ckeConfig: 97ddd7ba-c25a-4043-a699-94f190c43cd2 # Default
  columnType: text
  defaultTransform: ''
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
