columnSuffix: null
contentColumnType: string
handle: footerLinks
instructions: 'This will be the bottom icons and links in your footer going out to facebook, youtube, insta etc etc'
name: 'Footer Links'
searchable: false
settings:
  entryTypes:
    -
      uid: 95e3be53-2293-4333-904c-5f7a07242a54
  maxEntries: null
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
