columnSuffix: null
handle: headerImageAlt
instructions: null
name: 'Header Image Alt'
searchable: false
settings:
  byteLimit: null
  charLimit: 180
  code: false
  initialRows: 4
  multiline: false
  placeholder: 'This is the tags for images for google search'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
