columnSuffix: null
contentColumnType: string
handle: listencta
instructions: 'This is to create buttons on the home page e.g. "Listen on Spotify" etc...'
name: ListenCTA
searchable: false
settings:
  entryTypes:
    -
      uid: 93f4fd03-7ec3-4149-b30e-3d6a701d64a4
  maxEntries: null
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
