columnSuffix: null
handle: navPageLink
instructions: 'Use this to link to an internal page. Internal Page links will take precedence over external pages. Please choose one or the other.'
name: 'Nav Item - Nav Item - Nav Page Link'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  defaultPlacement: end
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  selectionLabel: null
  showCardsInGrid: false
  showSiteMenu: true
  showUnpermittedEntries: true
  showUnpermittedSections: true
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Entries
