columnSuffix: null
handle: state2
instructions: 'This will be shown as the  The 2 letters state abbreviations: e.g. NY, FL, GA ...'
name: 'Tour Dates - Dates - State'
searchable: false
settings:
  byteLimit: null
  charLimit: 2
  code: false
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
