columnSuffix: null
handle: time2
instructions: 'Time show starts'
name: 'Tour Dates - Dates - time'
searchable: false
settings:
  max: null
  min: null
  minuteIncrement: 5
translationKeyFormat: null
translationMethod: none
type: craft\fields\Time
