columnSuffix: null
contentColumnType: time
handle: time
instructions: 'Time show starts'
name: time
searchable: false
settings:
  max: null
  min: null
  minuteIncrement: 5
translationKeyFormat: null
translationMethod: none
type: craft\fields\Time
