columnSuffix: null
contentColumnType: string
handle: tourDates
instructions: null
name: 'Tour Dates'
searchable: false
settings:
  entryTypes:
    -
      uid: 0408c66a-7daf-4481-afc7-2ac098e1e927
  maxEntries: null
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
