columnSuffix: null
contentColumnType: string
handle: videos
instructions: null
name: Videos
searchable: false
settings:
  entryTypes:
    -
      uid: 5a99c46a-feb8-4904-a355-2715e51e048a
  maxEntries: null
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
