dateModified: 1759464976
elementSources:
  craft\elements\Entry:
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: '*'
      tableAttributes:
        - status
        - section
        - postDate
        - expiryDate
        - link
      type: native
    -
      defaultSort:
        - title
        - asc
      defaultViewMode: ''
      disabled: false
      key: singles
      tableAttributes:
        - status
        - link
      type: native
    -
      heading: Channels
      key: 'heading:1ac36f9f-8c73-4e13-8a45-01e4219f5c7b'
      type: heading
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: 'section:4eb33154-2538-4037-9a27-198bbb7cfcfa' # Tour Dates
      tableAttributes:
        - postDate
        - expiryDate
        - link
        - 'field:458ab821-4880-4299-8232-f99733310016' # date
        - 'field:d55cabd7-d990-4dac-9ea9-cc3941a1421f' # time
        - 'field:5fb9f1f8-c038-4593-b349-8cda166cb8fb' # City
        - 'field:0886b236-4a38-40bd-abfa-21fdee1352d7' # State
      type: native
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: 'section:7e048754-9e2b-4fef-a0ec-1afa07efa29b' # Pages
      tableAttributes:
        - status
        - postDate
        - expiryDate
        - link
      type: native
    -
      heading: Nav
      key: 'heading:27483e0d-c4b9-47ac-84b9-8e5eba27cd30'
      type: heading
    -
      defaultSort:
        - structure
        - asc
      defaultViewMode: ''
      disabled: false
      key: 'section:85eff002-8100-42c8-a7a8-4532563dfd23' # Navigation
      tableAttributes:
        - status
        - postDate
        - expiryDate
        - link
      type: native
email:
  fromEmail: contact@daverudolphmusic.com
  fromName: 'Dave Rudolph'
  replyToEmail: daverudolphguitar@gmail.com
  template: null
  transportSettings:
    password: 'Dajr*2448'
    timeout: '10'
    username: daverudolphguitar
  transportType: craft\mail\transportadapters\Gmail
fs:
  uploads:
    hasUrls: true
    name: Uploads
    settings:
      path: '@webroot/uploads'
    type: craft\fs\Local
    url: /uploads/
graphql:
  publicToken:
    enabled: false
    expiryDate: null
meta:
  __names__:
    0faa9768-b53e-4216-a53d-7812596fdc94: Videos # Videos
    1e7716dd-da4e-4a82-9a4a-f4eb04970454: ListenCTA # ListenCTA
    4eb33154-2538-4037-9a27-198bbb7cfcfa: 'Tour Dates' # Tour Dates
    5e19d471-ef0b-4e95-9548-97c378c4b65d: 'Tour Dates' # Tour Dates
    5fb9f1f8-c038-4593-b349-8cda166cb8fb: City # City
    6b2b62f0-3eb1-45ad-b397-559af7de174b: 'Dave Guitar' # Dave Guitar
    7e048754-9e2b-4fef-a0ec-1afa07efa29b: Pages # Pages
    20cc593a-1deb-4cbb-b161-ee53c5a114d9: Entry # Entry
    66bdc090-1029-4da8-a10f-8e0bc54176bb: spotifyIframes # spotifyIframes
    75d85378-d455-4ff4-bda0-9a51e95d30f9: Lightswitch # Lightswitch
    83f1bea5-400c-4373-8b03-cd7de4219b6c: 'Matrix Entry Type' # Matrix Entry Type
    85eff002-8100-42c8-a7a8-4532563dfd23: Navigation # Navigation
    429c85c0-0ce1-4713-a254-7b8a2e585e95: 'Spotify Album Block' # Spotify Album Block
    458ab821-4880-4299-8232-f99733310016: date # date
    502b621a-4cc7-4a26-a910-042f30dca048: Home # Home
    569d7efe-e957-4fa0-a49a-c4b1b8fba23b: 'Album Cover' # Album Cover
    0886b236-4a38-40bd-abfa-21fdee1352d7: State # State
    3304aae1-f09c-4687-bbe6-e0903dad9f0d: 'Nav Item' # Nav Item
    8972e6e4-7db5-4a0a-85b9-11be3f170a55: 'Custom Content' # Custom Content
    024543db-feed-428a-922b-5c42d8374aaa: 'Album CTA' # Album CTA
    510624a0-5eb7-469d-80ad-f0fd8770b0c6: Image # Image
    885183e7-a46e-417d-888c-fca4f7e1734d: Uploads # Uploads
    17303915-9872-43ed-9684-e3ae9e8d6099: 'Open In new Tab' # Open In new Tab
    56361854-6cef-42f0-b788-03399c9f683b: 'Dave Guitar' # Dave Guitar
    b43bae05-d6b6-4b8a-84bc-f01097e47529: Navigation # Navigation
    b242a145-18ec-45dd-a31a-28e9e48279c0: TOUR # TOUR
    b6502537-1c47-451c-8402-2f8dcde9a941: spotifyIframe # spotifyIframe
    c2111dd9-d621-4db5-9121-04eba429d67a: Home # Home
    cd2fbe89-ae24-4f97-a4e1-77aaf39f0a88: 'Footer Link' # Footer Link
    d2d8c823-93e6-4574-a238-533954b4b8b9: Default # Default
    d55cabd7-d990-4dac-9ea9-cc3941a1421f: time # time
    daaeae58-7e1f-4ad5-b1e5-18ac93440c24: 'Tour Dates' # Tour Dates
    df3eb26c-d215-44f0-a235-413cdb54c672: 'External Page' # External Page
    e025fb83-6598-430d-9ab8-5d4ced49979a: 'info url' # info url
    e819b4cf-0c03-4d0e-a011-c3af102e306f: 'Footer Links' # Footer Links
    e3406de7-2a12-435b-9899-630c47926027: 'Page Type' # Page Type
    ed2878ee-102f-406d-b62d-3d231fd7460b: 'Header Image Alt' # Header Image Alt
    eef00113-cbb0-4694-a0b5-70dbfd82c243: 'Internal or External' # Internal or External
    ef74887a-7a07-4977-84c2-c7793e0529a5: 'Header Image' # Header Image
plugins:
  aws-s3:
    edition: standard
    enabled: true
    schemaVersion: '2.0'
  contact-form:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      allowAttachments: ''
      prependSender: 'On behalf of You website'
      prependSubject: 'New message from daverudolphmusic.com'
      successFlashMessage: 'Your message has been sent.'
      toEmail: daverudolphguitar@gmail.com
  date-range:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  express-forms:
    edition: lite
    enabled: true
    schemaVersion: 1.0.2
  freeform:
    edition: express
    enabled: true
    schemaVersion: 5.6.2
    settings:
      alertNotificationRecipients: null
      allowBuilderTemplateCreation: true
      allowDashesInFieldHandles: false
      allowFileTemplateEdit: '1'
      autoScroll: true
      autoScrollToErrors: true
      badgeType: all
      blockedEmails: null
      blockedEmailsError: 'Invalid Email Address'
      blockedIpAddresses: null
      blockedKeywords: null
      blockedKeywordsError: 'Invalid Entry Data'
      bypassSpamCheckOnLoggedInUsers: false
      clientDigestFrequency: 1
      clientDigestRecipients: null
      csrfRefresh: none
      defaultFromEmail: '{{ general.systemEmail }}'
      defaultFromName: '{{ general.systemName }}'
      defaultView: forms
      defaults:
        __assoc__:
          -
            - previewHtml
            - true
          -
            - twigInHtml
            - true
          -
            - twigIsolation
            - true
          -
            - richTextFieldToolbarConfiguration
            - 'blocks bold italic underline forecolor backcolor | align numlist bullist | link image table | removeformat code'
          -
            - includeSampleTemplates
            - true
          -
            - notifications
            -
              __assoc__:
                -
                  - admin
                  -
                    __assoc__:
                      -
                        - template
                        -
                          __assoc__:
                            -
                              - locked
                              - false
                            -
                              - value
                              - ''
                -
                  - conditional
                  -
                    __assoc__:
                      -
                        - template
                        -
                          __assoc__:
                            -
                              - locked
                              - false
                            -
                              - value
                              - ''
                -
                  - userSelect
                  -
                    __assoc__:
                      -
                        - template
                        -
                          __assoc__:
                            -
                              - locked
                              - false
                            -
                              - value
                              - ''
                -
                  - emailField
                  -
                    __assoc__:
                      -
                        - template
                        -
                          __assoc__:
                            -
                              - locked
                              - false
                            -
                              - value
                              - ''
          -
            - settings
            -
              __assoc__:
                -
                  - general
                  -
                    __assoc__:
                      -
                        - formType
                        -
                          __assoc__:
                            -
                              - locked
                              - false
                            -
                              - value
                              - ''
                      -
                        - submissionTitle
                        -
                          __assoc__:
                            -
                              - locked
                              - false
                            -
                              - value
                              - '{{ dateCreated|date("Y-m-d H:i:s") }}'
                      -
                        - formattingTemplate
                        -
                          __assoc__:
                            -
                              - locked
                              - false
                            -
                              - value
                              - basic-light/index.twig
                -
                  - dataStorage
                  -
                    __assoc__:
                      -
                        - storeData
                        -
                          __assoc__:
                            -
                              - locked
                              - false
                            -
                              - value
                              - true
                      -
                        - defaultStatus
                        -
                          __assoc__:
                            -
                              - locked
                              - false
                            -
                              - value
                              - 2
                      -
                        - collectIp
                        -
                          __assoc__:
                            -
                              - locked
                              - false
                            -
                              - value
                              - true
                -
                  - processing
                  -
                    __assoc__:
                      -
                        - ajax
                        -
                          __assoc__:
                            -
                              - locked
                              - false
                            -
                              - value
                              - true
                      -
                        - showIndicator
                        -
                          __assoc__:
                            -
                              - locked
                              - false
                            -
                              - value
                              - true
                      -
                        - showText
                        -
                          __assoc__:
                            -
                              - locked
                              - false
                            -
                              - value
                              - true
                      -
                        - processingText
                        -
                          __assoc__:
                            -
                              - locked
                              - false
                            -
                              - value
                              - Processing...
                -
                  - successAndErrors
                  -
                    __assoc__:
                      -
                        - successBehavior
                        -
                          __assoc__:
                            -
                              - locked
                              - false
                            -
                              - value
                              - reload
                      -
                        - returnUrl
                        -
                          __assoc__:
                            -
                              - locked
                              - false
                            -
                              - value
                              - ''
                      -
                        - successTemplate
                        -
                          __assoc__:
                            -
                              - locked
                              - false
                            -
                              - value
                              - ''
                      -
                        - successMessage
                        -
                          __assoc__:
                            -
                              - locked
                              - false
                            -
                              - value
                              - 'Form has been submitted successfully!'
                      -
                        - errorMessage
                        -
                          __assoc__:
                            -
                              - locked
                              - false
                            -
                              - value
                              - 'Sorry, there was an error submitting the form. Please try again.'
                -
                  - limits
                  -
                    __assoc__:
                      -
                        - duplicateCheck
                        -
                          __assoc__:
                            -
                              - locked
                              - false
                            -
                              - value
                              - no_limit
      digestFrequency: 1
      digestOnlyOnProduction: false
      digestRecipients: null
      displayFeed: true
      emailNotificationToolbarConfiguration: 'blocks bold italic underline forecolor backcolor | align numlist bullist | link image table | removeformat code'
      emailTemplateDefault: database
      emailTemplateDirectory: ''
      emailTemplateMethod: form
      emailTemplateStorageType: files_database
      exportHandlesAsNames: false
      exportLabels: false
      fillWithGet: false
      footerScripts: false
      formFieldShowOnlyAllowedForms: false
      formSubmitDisable: true
      formSubmitExpiration: null
      formTemplateDirectory: _freeform
      formattingTemplate: basic-light/index.twig
      loggingLevel: error
      minimumSubmitTime: null
      pluginName: null
      purgableSpamAgeInDays: null
      purgableSubmissionAgeInDays: null
      purgableUnfinalizedAssetAgeInMinutes: 180
      purgeAssets: true
      queuePriority: null
      rememberPageSubmitOrder: true
      removeNewlines: false
      renderFormHtmlInCpViews: true
      saveFormSessionLimit: 10
      saveFormTtl: 30
      scriptInsertLocation: footer
      scriptInsertType: files
      sessionContext: payload
      sessionContextCount: 100
      sessionContextSecret: ''
      sessionContextTimeToLiveMinutes: 180
      sessionEntryMaxCount: 50
      sessionEntryTTL: 10800
      showErrorsForBlockedEmails: false
      showErrorsForBlockedKeywords: false
      sitesEnabled: false
      spamFolderEnabled: true
      spamProtectionBehavior: simulate_success
      submissionThrottlingCount: null
      submissionThrottlingTimeFrame: null
      successTemplateDirectory: ''
      updateSearchIndexes: true
      useQueueForEmailNotifications: false
      useQueueForIntegrations: false
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  sprig:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
  sprout-forms:
    enabled: false
    schemaVersion: 3.11.8
    settings:
      captchaSettings:
        barrelstrength\sproutforms\captchas\DuplicateCaptcha:
          enabled: 0
        barrelstrength\sproutforms\captchas\HoneypotCaptcha:
          enabled: 0
          honeypotFieldName: sprout-forms-hc
          honeypotScreenReaderMessage: 'Leave this field blank'
        barrelstrength\sproutforms\captchas\JavascriptCaptcha:
          enabled: 1
      cleanupProbability: 1000
      defaultSection: entries
      enableEditFormEntryViaFrontEnd: false
      enableSaveData: true
      enableSaveDataDefaultValue: true
      formTemplateId: barrelstrength\sproutforms\formtemplates\AccessibleTemplates
      pluginNameOverride: ''
      saveSpamToDatabase: false
      showNotificationsTab: true
      showReportsTab: true
      spamLimit: 500
      spamRedirectBehavior: redirectAsNormal
      trackRemoteIp: false
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: 'Dave Guitar'
  retryDuration: null
  schemaVersion: 5.8.0.3
  timeZone: America/Chicago
users:
  allowPublicRegistration: false
  deactivateByDefault: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
