defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 1e6e3839-9a1e-4d98-a6f8-13b7cd0097d7 # Default
handle: blog
maxAuthors: 1
name: Blog
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  56361854-6cef-42f0-b788-03399c9f683b: # Dave Guitar
    enabledByDefault: true
    hasUrls: true
    template: blog-entry
    uriFormat: 'blog/{slug}'
type: channel
