defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 2cb0502e-6cdf-449e-b6c3-d1297d2c6b45 # Contact
handle: contact
maxAuthors: 1
name: Contact
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  56361854-6cef-42f0-b788-03399c9f683b: # Dave Guitar
    enabledByDefault: true
    hasUrls: true
    template: contact
    uriFormat: contact
type: single
