defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: e4343257-eacd-41fb-b2d1-0ac429892afc # Media
handle: media
maxAuthors: 1
name: Media
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  56361854-6cef-42f0-b788-03399c9f683b: # Dave Guitar
    enabledByDefault: true
    hasUrls: true
    template: media
    uriFormat: media
type: single
