defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 6f3a48db-efe7-4a2e-b25d-509fbd2ff05d # Music
handle: music
maxAuthors: 1
name: Music
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  56361854-6cef-42f0-b788-03399c9f683b: # Dave Guitar
    enabledByDefault: true
    hasUrls: true
    template: music
    uriFormat: music
type: single
