defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    handle: default
    uid: d2d8c823-93e6-4574-a238-533954b4b8b9 # Default
handle: navigation
maxAuthors: 1
name: Navigation
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  56361854-6cef-42f0-b788-03399c9f683b: # Dave Guitar
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 2
  uid: a2db335f-e994-4433-9656-dd2186631736
type: structure
