defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: e28be8c5-7bcd-4e2b-9189-1f72f75ec7b4 # Tour
handle: tour
maxAuthors: 1
name: Tour
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  56361854-6cef-42f0-b788-03399c9f683b: # Dave Guitar
    enabledByDefault: true
    hasUrls: true
    template: tour
    uriFormat: tour
type: single
