defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 5e19d471-ef0b-4e95-9548-97c378c4b65d # Tour Dates
handle: tourDates
maxAuthors: 1
name: 'Tour Dates'
propagationMethod: all
siteSettings:
  56361854-6cef-42f0-b788-03399c9f683b: # Dave Guitar
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
